DROP TABLE IF EXISTS cclh;

CREATE TABLE `cclh` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO cclh(nombre) VALUES
('Admin');